#!/bin/sh

set -x
{
  `which glibtoolize 2>&1 >/dev/null`
  if [ $? -eq 0 ]; then
    glibtoolize --automake
  else
    libtoolize --automake
  fi
}
autopoint
aclocal -I m4 -I m4/gnulib
autoheader
automake --add-missing
autoconf
