.TH NFDUMP 1 "August 2004" "Newts" "Newts Reference Manual"

.SH NAME
nfdump \- create a saved image of a notesfile

.SH SYNOPSIS
.B nfdump
[\fIoptions\fR] \fINOTESFILE\fR...

.SH DESCRIPTION
.B nfdump
creates a plaintext dump of a notesfile which can be loaded back into Newts
with \fBnfload\fR(1).

.SH OPTIONS

\fB\-e\fR, \fB\-\^\-extension\fR=\fIEXT\fR
Specify the extension to be appended to the dump file or files created.  The
notesfile name will have a period and then this extension appended to create
the dump file name.  The default is `dump'.

.TP
\fB\-h\fR, \fB\-\^\-help\fR
Print a summary of usage and command-line options for
.B nfdump
and exit.

.TP
\fB\-v\fR, \fB\-\^\-verbose\fR
Print a confirmation message for each successfully processed notesfile.

.TP
\fB\-\^\-debug\fR
Print debugging messages to standard error.

.TP
\fB\-\^\-version\fR
Print version information for
.B nfdump
and exit.

.SH AUTHOR
.B Newts
was written and is maintained by Tyler Berry <tyler+newts@thoughtlocker.net>.

.SH SEE ALSO
\fBautoseq\fR(1), \fBchecknotes\fR(1), \fBgetnote\fR(1), \fBmknf\fR(1),
\fBnfadmin\fR(1), \fBnfload\fR(1), \fBnfmail\fR(1), \fBnfpipe\fR(1),
\fBnfprint\fR(1), \fBnfstats\fR(1), \fBnftimestamp\fR(1), \fBnotes\fR(1),
\fBrmnf\fR(1)

The full documentation for
.B Newts
is maintained as a Texinfo manual.  If the
.B info
and
.B Newts
programs are properly installed at your site, the command
.IP
.B info newts
.PP
should give you access to the complete manual.
